spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/exercise
    username: root
    password:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#      type:
#        descriptor:
#          sql:
#            BasicBinder: trace

